/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyPropertyIdRouteImport } from './routes/property.$propertyId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyPropertyIdRoute = PropertyPropertyIdRouteImport.update({
  id: '/property/$propertyId',
  path: '/property/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/saved' | '/search' | '/property/$propertyId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/saved' | '/search' | '/property/$propertyId'
  id: '__root__' | '/' | '/saved' | '/search' | '/property/$propertyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  PropertyPropertyIdRoute: typeof PropertyPropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$propertyId': {
      id: '/property/$propertyId'
      path: '/property/$propertyId'
      fullPath: '/property/$propertyId'
      preLoaderRoute: typeof PropertyPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  PropertyPropertyIdRoute: PropertyPropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
